[package]
name = "novadraw"
version.workspace = true
edition.workspace = true

[dependencies]
glam = { workspace = true }
slotmap = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
