[package]
name = "editor"
version.workspace = true
edition.workspace = true

[dependencies]
winit = "0.30.12"
log = { workspace = true }
env_logger = { workspace = true }
novadraw = { path = "../../novadraw", features = ["vello", "debug_render"] }
pollster = "0.4.0"
glam = { workspace = true }
