[package]
name = "novadraw-geometry"
version.workspace = true
edition.workspace = true

[dependencies]
glam.workspace = true
kurbo = "0.11"
serde = { workspace = true }
novadraw-math = { path = "../novadraw-math" }
